### ISSUE TITLE
Add the ability to add new sections to the current card.

### ISSUE THREAD

**Issue by jacob-and-nathan** [jacob-and-nathan/SoftwarePlanner#16]
It has already been started but isn't completely ready yet.

**Comment by carlosrrod** [comment]
Good work so far. I'll work on creating multiple cards, as I did so in the first pull request and you can continue working on the other parts, that way we don't get any conflicts when we merge branches. 

Regarding your comment on **line 41** No, you can't really add placeholder text to a `div` but you can add text using `.innerText` so that would look something like:
`  projectCardBody.innerText = 'Enter project description';` or something like this.

Also, our app.js file is getting a little large, do you think we should break it up into modules? I think we could move the entire `createCard` function and turn it into a class and give it methods to handle when to allow edits to the card and to delete the card, etc. I'll let you decide!

**Comment by jacob-and-nathan** [comment]
Yes, that should work quite well. Regarding **line 41** I decided not to put the `.innerText` code because it would be quite annoying for the user to have to delete it every time they want to type in text. But, if I can find a way to delete all the text inside the block the VERY first time you click on it, I probably will do that.

Regarding **app.js,** right now, I don't think it's **too** big, but once it starts to get to 150-200 lines, I might do that!

**Comment by jacob-and-nathan** [comment]
Also, would you be able to assign yourself to the issue called 'Add the ability to add multiple cards,' just so that I can keep things organised?
