### ISSUE TITLE
Add the ability to add multiple cards

### ISSUE THREAD

**Issue by jacob-and-nathan** [jacob-and-nathan/SoftwarePlanner#17]

**Comment by carlosrrod** [comment]
I don't have write permissions so you'll have to assign me to this issue yourself.

**Comment by carlosrrod** [comment]
I created a pull request. Users can now create multiple cards. I also added code so that the placeholder card only appears if no cards are on screen. Also added styling to deal with mobile views. 

The styling for the button to add multiple cards is not the same from the original, to make things simple, the button is positioned using `position: absolute;` this allows me to hide the button without it affecting the placement of the other cards. This was just my solution, if you have a better one then feel free to implement it.

**Comment by jacob-and-nathan** [comment]
Thank you very much - I might experiment with other solutions, but for now it will be fine!
